services:
  obsidian-search:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./vault:/vault:ro
      - ./chroma_data:/app/db
    environment:
      - VAULT_PATH=/vault
      - DB_PATH=/app/db
      - ENABLE_TELEGRAM_BOT=${ENABLE_TELEGRAM_BOT:-False}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - API_KEY=${API_KEY}
      - OPENROUTER_KEY=${OPENROUTER_KEY}

    restart: unless-stopped
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./obsidian_config:/config
      - ./vault:/vault
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
