services:
  obsidian-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./vault:/vault:ro
      - ./chroma_data:/app/db
    environment:
      - VAULT_PATH=/vault
      - DB_PATH=/app/db
      - API_KEY=${API_KEY}
    networks:
      - app-network
    restart: unless-stopped

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.telegram-bot
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - API_KEY=${API_KEY}
      - OPENROUTER_KEY=${OPENROUTER_KEY}
      - API_URL=http://obsidian-api:8000
    depends_on:
      - obsidian-api
    networks:
      - app-network
    restart: unless-stopped

  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./obsidian_config:/config
      - ./vault:/vault
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - app-network
    shm_size: "1gb"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
